package View;

import Controller.Usability;
import Model.Cliente;
import Model.Conta;
import Model.ContaCorrente;
import Model.ContaInvestimento;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nilo-
 */
public class Clientes extends javax.swing.JFrame {
    private ClienteTableModel tableCliente = new ClienteTableModel(); 
    private ContasTableModel tableConta = new ContasTableModel();
    private Cliente clienteSelecionado;
    private Conta contaSelecionada;
    private int linhaClicada = -1;
    private int linhaClicadaVinc = -1;
    private int linhaClicadaContas = -1;
    /**
     * Creates new form NewJFrame
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nomeText = new javax.swing.JTextField();
        cpfText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endereçoText = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        atualizartButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sobrenomeText = new javax.swing.JTextField();
        rgText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        removerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clienteVincTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        nomeVincText = new javax.swing.JTextField();
        tipoContaComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        contaProps = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        depInicText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        depMinLimText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        montMinText = new javax.swing.JTextField();
        VincularButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cpfVincText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rgVincText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        contasTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cpfPesqText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nrContaLabel = new javax.swing.JLabel();
        nomeDonoContaText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        valorText = new javax.swing.JTextField();
        sacarButton = new javax.swing.JButton();
        depButton = new javax.swing.JButton();
        saldoButton = new javax.swing.JButton();
        remButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        cpfText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("RG");

        jLabel3.setText("Nome");

        jLabel4.setText("Endereço");

        endereçoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereçoTextActionPerformed(evt);
            }
        });

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        atualizartButton.setText("Atualizar");
        atualizartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizartButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Sobrenome");

        sobrenomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeTextActionPerformed(evt);
            }
        });

        rgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgTextActionPerformed(evt);
            }
        });

        clienteTable.setModel(tableCliente);
        clienteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clienteTable);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(endereçoText, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atualizartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sobrenomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rgText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(rgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endereçoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarButton)
                            .addComponent(atualizartButton)
                            .addComponent(removerButton))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Clientes", jPanel1);

        clienteVincTable.setModel(tableCliente);
        clienteVincTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteVincTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clienteVincTable);

        jLabel5.setText("Nome");

        nomeVincText.setEditable(false);

        tipoContaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione","Conta corrente", "Conta Investimento"}));
        tipoContaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoContaComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de conta");

        jLabel10.setText("Depósito inicial");

        jLabel11.setText("Depósito minimo");

        jLabel12.setText("Montante minimo");

        montMinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montMinTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contaPropsLayout = new javax.swing.GroupLayout(contaProps);
        contaProps.setLayout(contaPropsLayout);
        contaPropsLayout.setHorizontalGroup(
            contaPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaPropsLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depInicText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depMinLimText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(montMinText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contaPropsLayout.setVerticalGroup(
            contaPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contaPropsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contaPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(depInicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(depMinLimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(montMinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contaProps.setVisible(false);

        VincularButton.setText("Vincular");
        VincularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VincularButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF");

        cpfVincText.setEditable(false);
        cpfVincText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfVincTextActionPerformed(evt);
            }
        });

        jLabel13.setText("RG");

        rgVincText.setEditable(false);
        rgVincText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgVincTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoContaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contaProps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VincularButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeVincText, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfVincText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rgVincText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(VincularButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomeVincText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cpfVincText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(rgVincText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipoContaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(contaProps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Vincular Cliente", jPanel2);

        contasTable.setModel(tableConta);
        contasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contasTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(contasTable);

        jLabel14.setText("CPF");

        cpfVincText.setEditable(false);
        cpfPesqText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfPesqTextActionPerformed(evt);
            }
        });
        cpfPesqText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfPesqTextKeyPressed(evt);
            }
        });

        jLabel8.setText("Nº");

        nomeVincText.setEditable(false);

        jLabel16.setText("Nome");

        jLabel17.setText("Valor");

        valorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTextActionPerformed(evt);
            }
        });

        sacarButton.setText("Sacar");
        sacarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarButtonActionPerformed(evt);
            }
        });

        depButton.setText("Depositar");
        depButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depButtonActionPerformed(evt);
            }
        });

        saldoButton.setText("Ver Saldo");
        saldoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoButtonActionPerformed(evt);
            }
        });

        remButton.setText("Remunerar");
        remButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeDonoContaText, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cpfPesqText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nrContaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sacarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cpfPesqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sacarButton)
                    .addComponent(depButton)
                    .addComponent(nrContaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nomeDonoContaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoButton)
                    .addComponent(remButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Contas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextActionPerformed

    private void rgTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgTextActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        if(todosCamposPreenchidos()){
            Cliente c = new Cliente(nomeText.getText(), sobrenomeText.getText(), rgText.getText(), cpfText.getText(), endereçoText.getText());
                        
            tableCliente.adicionaCliente(c);

            linhaClicada = -1;
            limpaFormulario();
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void sobrenomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeTextActionPerformed

    private void atualizartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizartButtonActionPerformed
        if(linhaClicada != -1){
             Cliente c = new Cliente(nomeText.getText(), sobrenomeText.getText(), rgText.getText(), cpfText.getText(), endereçoText.getText());
            tableCliente.atualizaCliente(linhaClicada, c);
            
            limpaFormulario();
            linhaClicada = -1;
        }
    }//GEN-LAST:event_atualizartButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        if(linhaClicada != -1){
            
            int response = JOptionPane.showConfirmDialog(this, "Deseja remover o cliente "+clienteSelecionado.getNome()+" ?\nTodas as contas referente a esse cliente serão apagadas.");
            if(response == JOptionPane.YES_OPTION){
                tableCliente.removeCliente(clienteSelecionado);

                limpaFormulario();
                linhaClicada = -1;
            }            
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void clienteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteTableMouseClicked
        linhaClicada = clienteTable.rowAtPoint(evt.getPoint());
        clienteSelecionado = tableCliente.getCliente(linhaClicada);
        
        setFormulario(clienteSelecionado);
    }//GEN-LAST:event_clienteTableMouseClicked

    private void endereçoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereçoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereçoTextActionPerformed

    private void clienteVincTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteVincTableMouseClicked
        linhaClicadaVinc = clienteVincTable.rowAtPoint(evt.getPoint());
        clienteSelecionado = tableCliente.getCliente(linhaClicadaVinc);
        
        if(!clienteSelecionado.isPossuiConta())
            setFormularioVincular(clienteSelecionado);
    }//GEN-LAST:event_clienteVincTableMouseClicked

    private void montMinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montMinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montMinTextActionPerformed

    private void VincularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VincularButtonActionPerformed
        int contaOpc = tipoContaComboBox.getSelectedIndex();
        int numeroConta = Usability.contas.size()+1;
        Conta c;
        if(linhaClicadaVinc == -1)
            return;
        switch (contaOpc){
            case 1:
                c = new ContaCorrente(Double.parseDouble(depMinLimText.getText()), numeroConta, clienteSelecionado);
                if(!c.deposita(Double.parseDouble(depInicText.getText()))){
                     JOptionPane.showMessageDialog(this, "Não foi possivel vincular cliente a conta");
                     return;
                }                    
                c.getDono().setPossuiConta(true);
                tableConta.adicionaConta(c);
                break;
            case 2:
                c = new ContaInvestimento(Double.parseDouble(depMinLimText.getText()),Double.parseDouble(montMinText.getText()), numeroConta, clienteSelecionado);
                if(!c.deposita(Double.parseDouble(depInicText.getText()))){
                     JOptionPane.showMessageDialog(this, "Não foi possivel vincular cliente a conta");
                     return;
                } 
                c.getDono().setPossuiConta(true);
                tableConta.adicionaConta(c);
                break;
            default: 
                contaProps.setVisible(false);
       }
        linhaClicadaVinc = -1;
        limpaFormularioVincular();
    }//GEN-LAST:event_VincularButtonActionPerformed

    private void cpfVincTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfVincTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfVincTextActionPerformed

    private void rgVincTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgVincTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgVincTextActionPerformed

    private void tipoContaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoContaComboBoxActionPerformed
       int contaOpc = tipoContaComboBox.getSelectedIndex();
       switch (contaOpc){
            case 1:
                jLabel11.setText("Limite");
                jLabel12.setVisible(false);
                montMinText.setVisible(false);
                contaProps.setVisible(true);                
                break;
            case 2:
                jLabel11.setText("Depósito minimo");
                jLabel12.setVisible(true);
                montMinText.setVisible(true);
                contaProps.setVisible(true);
                break;
            default: 
                contaProps.setVisible(false);
       }
    }//GEN-LAST:event_tipoContaComboBoxActionPerformed

    private void contasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasTableMouseClicked
        linhaClicadaContas = contasTable.rowAtPoint(evt.getPoint());
        contaSelecionada = tableConta.getConta(linhaClicadaContas);
        
        setFormularioConta(contaSelecionada);
    }//GEN-LAST:event_contasTableMouseClicked

    private void cpfPesqTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfPesqTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfPesqTextActionPerformed

    private void sacarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarButtonActionPerformed
        if(linhaClicadaContas == -1)
            return;
        
        double valor = Double.parseDouble(valorText.getText());
        if(contaSelecionada.saca(valor))
            JOptionPane.showMessageDialog(this, "Saque realizado!");
        else
            JOptionPane.showMessageDialog(this, "Não foi possivel realizar o saque.");
    }//GEN-LAST:event_sacarButtonActionPerformed

    private void valorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTextActionPerformed

    private void cpfPesqTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfPesqTextKeyPressed
       String cpf = cpfPesqText.getText();
       List<Conta> novaLista = Usability.contas.stream().filter(c -> c.getDono().getCpf().contains(cpf)).collect(Collectors.toList());
       
       tableConta.atualizarTabela(novaLista);
    }//GEN-LAST:event_cpfPesqTextKeyPressed

    private void saldoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoButtonActionPerformed
        if(linhaClicadaContas == -1)
            return;
        
        JOptionPane.showMessageDialog(this, "O Saldo da conta "+contaSelecionada.getNumero()+" é: "+contaSelecionada.getSaldo());
    }//GEN-LAST:event_saldoButtonActionPerformed

    private void remButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButtonActionPerformed
       if(linhaClicadaContas == -1)
            return;
        
        contaSelecionada.remunera();
        JOptionPane.showMessageDialog(this, "Conta "+contaSelecionada.getNumero()+" remunerada!");
       
    }//GEN-LAST:event_remButtonActionPerformed

    private void depButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depButtonActionPerformed
        if(linhaClicadaContas == -1)
            return;
        
        double valor = Double.parseDouble(valorText.getText());
        if(contaSelecionada.deposita(valor))
            JOptionPane.showMessageDialog(this, "Depósito realizado!");
        else
            JOptionPane.showMessageDialog(this, "Não foi possivel realizar o depósito.");
    }//GEN-LAST:event_depButtonActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        limpaFormulario();
        limpaFormularioVincular();
        limpaFormularioConta();
        
        linhaClicada = -1;
        linhaClicadaVinc = -1;
        linhaClicadaContas = -1;
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void limpaFormulario(){
        nomeText.setText(null);
        sobrenomeText.setText(null);
        rgText.setText(null);
        cpfText.setText(null);
        endereçoText.setText(null);
    }
    
    private void setFormulario(Cliente c){
        nomeText.setText(c.getNome());
        sobrenomeText.setText(c.getSobrenome());
        rgText.setText(c.getRg());
        cpfText.setText(c.getCpf());
        endereçoText.setText(c.getEndereço());
    }
    
    private void setFormularioVincular(Cliente c){
        nomeVincText.setText(c.getNome()+" "+ c.getSobrenome());
        cpfVincText.setText(c.getCpf());
        rgVincText.setText(c.getRg());
    }
    
    private void limpaFormularioVincular(){
        nomeVincText.setText(null);
        cpfVincText.setText(null);
        rgVincText.setText(null);
        depInicText.setText(null);
        depMinLimText.setText(null);
        montMinText.setText(null);
    }
    
    private boolean todosCamposPreenchidos(){
        return !(nomeText.getText() == null || nomeText.getText().equals("") ||
                sobrenomeText.getText() == null || sobrenomeText.getText().equals("") ||
                cpfText.getText() == null || cpfText.getText().equals("") ||
                rgText.getText() == null || rgText.getText().equals("") ||
                endereçoText.getText() == null || endereçoText.getText().equals(""));
    }
    
    private void setFormularioConta(Conta c) {
        nomeDonoContaText.setText(c.getDono().getNome()+" "+c.getDono().getSobrenome());
        nrContaLabel.setText(Integer.toString(c.getNumero()));
        cpfPesqText.setText(c.getDono().getCpf());
    }
    
    private void limpaFormularioConta() {
        nomeDonoContaText.setText(null);
        nrContaLabel.setText(null);
        cpfPesqText.setText(null);
        valorText.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VincularButton;
    private javax.swing.JButton atualizartButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTable clienteTable;
    private javax.swing.JTable clienteVincTable;
    private javax.swing.JPanel contaProps;
    private javax.swing.JTable contasTable;
    private javax.swing.JTextField cpfPesqText;
    private javax.swing.JTextField cpfText;
    private javax.swing.JTextField cpfVincText;
    private javax.swing.JButton depButton;
    private javax.swing.JTextField depInicText;
    private javax.swing.JTextField depMinLimText;
    private javax.swing.JTextField endereçoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField montMinText;
    private javax.swing.JTextField nomeDonoContaText;
    private javax.swing.JTextField nomeText;
    private javax.swing.JTextField nomeVincText;
    private javax.swing.JLabel nrContaLabel;
    private javax.swing.JButton remButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JTextField rgText;
    private javax.swing.JTextField rgVincText;
    private javax.swing.JButton sacarButton;
    private javax.swing.JButton saldoButton;
    private javax.swing.JTextField sobrenomeText;
    private javax.swing.JComboBox<String> tipoContaComboBox;
    private javax.swing.JTextField valorText;
    // End of variables declaration//GEN-END:variables

}
